### ISSUE TITLE
PS3 BD remote bluez plugin deleted?

### ISSUE THREAD

**Issue by Ashark** [kitlaan/xbmc-addon-executor#1]
Hello. On [this](https://kodi.wiki/view/Archive:Set_up_PS3_BD_Remote) page (an archived article in Kodi wiki) it was mentioned that you had a patched bluez version that allowed to pair the ps3 bd remote with linux. 
But currently the  http://kitlaan.twinaxis.com/projects/bluez-ps3remote/ link is dead.

Can you clarify what happened to the project? Was it just dropped? Or was its functionality included in some bluez plugin? Because I have such a remote and when I press start + enter and try to pair, it fails.

**Comment by kitlaan** [comment]
I stopped maintaining it when BlueZ 5.0 released, as it changed sufficiently that the patch would have to be completely rewritten.

Here's the last version I ever made: https://gist.github.com/kitlaan/245587a0c46884d0903370746b226575

**Comment by Ashark** [comment]
Thanks for the patch, please do not delete it, so somebody can analyze what was done there.
It is not easy to make it work on bluez 5+?
How did you achieved it? A lot of reverse engineering? The problem is not just in the pairing mechanism, but also in the data exchange itself, correct? Because previously I naively thought that it may work like a bluetooth keyboard, and I wanted to just remap its button to any action on linux pc.
Also, ps3 bd remote refuses to pair with Android device. It is not possible to also use it on Android, right?

**Comment by kitlaan** [comment]
BlueZ 5 changed a bunch of the underlying code, so it was nontrivial to figure out where to hook things properly.  IIRC (it's been a loooong time), I reimplemented the fakehid layer of the existing PS3 remote code to add in keymapping, as well as tweaking the pairing logic.

As far as I remember, the remote had a special pairing mechanism. So it's probably not likely to work anywhere without some special stuff.

**Comment by Ashark** [comment]
Thanks for clarification!
